name: 'Add existing app or test app'

run-name: "Add existing app or test app in [${{ github.ref_name }}]"

on:
  workflow_dispatch:
    inputs:
      project:
        description: Project name if the repository is setup for multiple projects
        required: false
        default: '.'
      url:
        description: Direct Download Url of .app or .zip file
        required: true
      directCommit:
        description: Direct COMMIT (Y/N)
        required: false
        default: 'N'
      useGhTokenWorkflow:
        description: Use GhTokenWorkflow for Pull Request/COMMIT
        type: boolean

permissions:
  contents: write
  pull-requests: write

defaults:
  run:
    shell: powershell

env:
  ALGoOrgSettings: ${{ vars.ALGoOrgSettings }}
  ALGoRepoSettings: ${{ vars.ALGoRepoSettings }}

jobs:
  AddExistingAppOrTestApp:
    runs-on: [ windows-latest ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Initialize the workflow
        id: init
        uses: aholstrup1/AL-Go/Actions/WorkflowInitialize@c3a13dda0943552a29399f0c04a709c22fd7b36c
        with:
          shell: powershell
          eventId: "DO0090"

      - name: Read settings
        uses: aholstrup1/AL-Go/Actions/ReadSettings@c3a13dda0943552a29399f0c04a709c22fd7b36c
        if: github.event.inputs.useGhTokenWorkflow == 'true'
        with:
          shell: powershell
          parentTelemetryScopeJson: ${{ steps.init.outputs.telemetryScopeJson }}

      - name: Read secrets
        uses: aholstrup1/AL-Go/Actions/ReadSecrets@c3a13dda0943552a29399f0c04a709c22fd7b36c
        if: github.event.inputs.useGhTokenWorkflow == 'true'
        with:
          shell: powershell
          parentTelemetryScopeJson: ${{ steps.init.outputs.telemetryScopeJson }}
          gitHubSecrets: ${{ toJson(secrets) }}
          getSecrets: 'ghTokenWorkflow'

      - name: CalculateToken
        id: CalculateToken
        env:
          useGhTokenWorkflow: ${{ github.event.inputs.useGhTokenWorkflow }}
        run: |
          $ghToken = '${{ secrets.GITHUB_TOKEN }}'
          if ($env:useGhTokenWorkflow -eq 'true') {
            $secrets = $env:Secrets | ConvertFrom-Json
            if ($secrets.GHTOKENWORKFLOW) {
              $ghToken = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String($secrets.GHTOKENWORKFLOW))
            }
            else {
              Write-Host "::Warning::GHTOKENWORKFLOW secret not found. Using GITHUB_TOKEN."
            }
          }
          Add-Content -Encoding UTF8 -Path $env:GITHUB_OUTPUT -Value "ghToken=$ghToken"

      - name: Add existing app
        uses: aholstrup1/AL-Go/Actions/AddExistingApp@c3a13dda0943552a29399f0c04a709c22fd7b36c
        with:
          shell: powershell
          token: ${{ steps.CalculateToken.outputs.ghToken }}
          parentTelemetryScopeJson: ${{ steps.init.outputs.telemetryScopeJson }}
          project: ${{ github.event.inputs.project }}
          url: ${{ github.event.inputs.url }}
          directCommit: ${{ github.event.inputs.directCommit }}

      - name: Finalize the workflow
        if: always()
        uses: aholstrup1/AL-Go/Actions/WorkflowPostProcess@c3a13dda0943552a29399f0c04a709c22fd7b36c
        with:
          shell: powershell
          eventId: "DO0090"
          telemetryScopeJson: ${{ steps.init.outputs.telemetryScopeJson }}
