name: ' Publish To AppSource'

on:
  workflow_dispatch:
    inputs:
      appVersion:
        description: App version to deliver to AppSource (current, prerelease, draft, latest or version number)
        required: false
        default: 'current'
      projects:
        description: Projects to publish to AppSource if the repository is multi-project. Default is *, which will publish all projects to AppSource.
        required: false
        default: '*'
      GoLive:
        description: Promote AppSource App to go live if it passes technical validation? (Y/N)
        required: false
        default: 'N'

permissions:
  contents: read
  actions: read

defaults:
  run:
    shell: powershell

env:
  ALGoOrgSettings: ${{ vars.ALGoOrgSettings }}
  ALGoRepoSettings: ${{ vars.ALGoRepoSettings }}

jobs:
  Initialization:
    runs-on: [ windows-latest ]
    outputs:
      telemetryScopeJson: ${{ steps.init.outputs.telemetryScopeJson }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Initialize the workflow
        id: init
        uses: aholstrup1/AL-Go/Actions/WorkflowInitialize@9e0b292d8c9dcf30c7a0bfc07ed4437b404fdc4d
        with:
          shell: powershell
          eventId: "DO0103"

  Deliver:
    needs: [ Initialization ]
    runs-on: [ windows-latest ]
    name: Deliver to AppSource
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Read settings
        uses: aholstrup1/AL-Go/Actions/ReadSettings@9e0b292d8c9dcf30c7a0bfc07ed4437b404fdc4d
        with:
          shell: powershell
          parentTelemetryScopeJson: ${{ needs.Initialization.outputs.telemetryScopeJson }}

      - name: Read secrets
        uses: aholstrup1/AL-Go/Actions/ReadSecrets@9e0b292d8c9dcf30c7a0bfc07ed4437b404fdc4d
        with:
          shell: powershell
          gitHubSecrets: ${{ toJson(secrets) }}
          getSecrets: 'appSourceContext'

      - name: DeliveryContext
        id: deliveryContext
        run: |
          $errorActionPreference = "Stop"; $ProgressPreference = "SilentlyContinue"; Set-StrictMode -Version 2.0
          $secrets = $env:Secrets | ConvertFrom-Json
          if ($secrets.appSourceContext) {
            $deliveryContext = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String($secrets.appSourceContext))
            Add-Content -Encoding UTF8 -Path $env:GITHUB_OUTPUT -Value "deliveryContext=$deliveryContext"
          }
          else {
            throw "appSourceContext secret is missing"
          }

      - name: Deliver
        uses: aholstrup1/AL-Go/Actions/Deliver@9e0b292d8c9dcf30c7a0bfc07ed4437b404fdc4d
        env:
          deliveryContext: '${{ steps.deliveryContext.outputs.deliveryContext }}'
        with:
          shell: powershell
          parentTelemetryScopeJson: ${{ needs.Initialization.outputs.telemetryScopeJson }}
          type: 'Release'
          projects: ${{ github.event.inputs.projects }}
          deliveryTarget: 'AppSource'
          artifacts: ${{ github.event.inputs.appVersion }}
          goLive: ${{ github.event.inputs.goLive }}

  PostProcess:
    if: always()
    runs-on: [ windows-latest ]
    needs: [ Initialization, Deliver ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Finalize the workflow
        id: PostProcess
        uses: aholstrup1/AL-Go/Actions/WorkflowPostProcess@9e0b292d8c9dcf30c7a0bfc07ed4437b404fdc4d
        with:
          shell: powershell
          eventId: "DO0103"
          telemetryScopeJson: ${{ needs.Initialization.outputs.telemetryScopeJson }}
